# -*- coding: utf-8 -*-
"""Int to binary.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iXVzGLoljQmI80oYQLcI8pxGUNIX89Nm
"""

import math

m = 916461
q = int((math.log(m, 2)))
num_2 = []
for i in range(q + 1):
    num_2.append(m % 2)
    m = m // 2
num_2.reverse()
normalize = "".join(map(str, num_2))
print('Your int num in binary system = ', int(normalize))
